# Nombre de la aplicación
spring.application.name=unilex

# Puerto de ejecución
server.port=8080

# Perfil activo
spring.profiles.active=dev

# Nivel de Log DEBUG para el paquete del proyecto (com.unilex.app.Unilex)
logging.level.com.unilex.app.Unilex=DEBUG